

all:	harmonic.cpp funks.cpp test.cpp
		# g++ helloworld.cpp -I/psth/to/include -o helloworld -L/path/to/libraries
		#clang++ -std=c++17 -Wall -pedantic harmonic.cpp -o harmonic
		g++ -std=c++17 -Wall -pedantic harmonic.cpp -o harmonic
		#clang++ -std=c++17 -Wall -pedantic funks.cpp -o funks
		g++ -std=c++17 -Wall -pedantic funks.cpp -o funks
		#clang++ -std=c++17 -Wall -pedantic test.cpp -o test	
		g++ -std=c++17 -Wall -pedantic test.cpp -o test	

harmonic:	harmonic.cpp
		#clang++ -std=c++17 -Wall -pedantic harmonic.cpp -o harmonic
		g++ -std=c++17 -Wall -pedantic harmonic.cpp -o harmonic

funks:	funks.cpp
		#clang++ -std=c++17 -Wall -pedantic funks.cpp -o funks
		g++ -std=c++17 -Wall -pedantic funks.cpp -o funks
