

all:	QCG.cpp chi2.cpp autocorr_test.cpp

QCG: QCG.cpp
		# g++ helloworld.cpp -I/psth/to/include -o helloworld -L/path/to/libraries
		clang++ -std=c++17 -Wall -pedantic QCG.cpp -o qcg

chi2: chi2.cpp
		# g++ helloworld.cpp -I/psth/to/include -o helloworld -L/path/to/libraries
		clang++ -std=c++17 -Wall -pedantic chi2.cpp -o chi2

autocorr: autocorr_test.cpp
		# g++ helloworld.cpp -I/psth/to/include -o helloworld -L/path/to/libraries
		clang++ -std=c++17 -Wall -pedantic autocorr_test.cpp -o autocorr

