

all:	QCG.cpp

QCG: QCG.cpp
		# g++ helloworld.cpp -I/psth/to/include -o helloworld -L/path/to/libraries
		clang++ -std=c++17 -Wall -pedantic QCG.cpp -o qcg
# rng: RNG.cpp
# 		clang++ -std=c++17 -Wall -pedantic RNG.cpp -o RNG
# 		gcc rng.h

